### ISSUE TITLE
Klucze w kodzie

### ISSUE THREAD

**Issue by youshy** [RafalWojciechRolsky/Serwis-Sklad#2]
https://github.com/RafalWojciechRolsky/Serwis-Sklad/blob/779c854594f1d0458647f0a78f29c6df3edec1f2/server/app.js#L11

Koniecznie wywal wszystkie klucze z kodu, jesli używasz dockera, to puszczaj je przez `.env` w kontenerze (a nawet jeśli nie, to też przez `.env` puszczaj)

**Comment by RafalWojciechRolsky** [comment]
Wiem o tym, miałem to zrobić i zapomniałem o tym, miałem to w privie a nie
publicu. mea culpa. jak widzisz jest tam dotenv zainstalowany, ale tego ne
dokończyłem, a potem zająłem sie czymś innym.

**Comment by RafalWojciechRolsky** [comment]
zrobione

**Comment by RafalWojciechRolsky** [comment]
Musze jeszcze pomyśleć jak je wywalić z historii ;) ale chyba najlepszym
sposobem będzie założenie nowej bazy

**Comment by youshy** [comment]
> Musze jeszcze pomyśleć jak je wywalić z historii ;) ale chyba najlepszym sposobem będzie założenie nowej bazy

Zanim to zrobisz to spróbuj się pobawić w czyszczenie commitów, to jest strasznie ciekawa rzecz :D

**Comment by RafalWojciechRolsky** [comment]
ale ja nie chce tracić zielonych znaczków na grafie czasu, a to się chyba
traci jak coś zakomitujesz, a potem to wywalisz :D to takie demotywujące ..
chyba, nie jestem pewny :D
