### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by youshy** [RafalWojciechRolsky/Serwis-Sklad#3]
https://github.com/RafalWojciechRolsky/Serwis-Sklad/blob/779c854594f1d0458647f0a78f29c6df3edec1f2/server/app.js#L34

Wygodniej jest zrobić sobie coś takiego: 

```javascript
const PORT = 4000

app.listen(PORT, () => { [...]
```

Dlatego, że jeśli będziesz wypuszczał aplikację na cluster, to może być o wiele lepiej podać port znów przez `.env` czy przez jakikolwiek plik konfiguracyjny - zostawiasz sobie wtedy ten wspaniały motyw skalowalności w kodzie.

**Comment by RafalWojciechRolsky** [comment]
To też wiem, ale wiadomo można było od razu to zrobić by potem o tym nie
pamiętać :)

**Comment by RafalWojciechRolsky** [comment]
zrobione
